CREATE TABLE IF NOT EXISTS public.users
(
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  username character varying(20) COLLATE pg_catalog."default" NOT NULL,
  hash bytea NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

-- Index: username
CREATE INDEX IF NOT EXISTS username
  ON public.users USING btree
  (username COLLATE pg_catalog."default" ASC NULLS LAST)
  TABLESPACE pg_default;